### ISSUE TITLE
Unable to browse, missing images

### ISSUE THREAD

**Issue by pmolvaer** [toota-toota/piflix#3]
It seems that something fails to load, both images and menu items.
This is the url when I click on movies and series: http://127.0.1.1:3000/#

The text works, I can read "Welcome to PiFlix" etc.. I can also see the Torrent and a play symbol.
I would attach a screenshot, but I am quite new to the raspbian, so I don*t know how to..

**Comment by baskervald** [comment]
Since raspbian seems to run x11, you can run `scrot <filename>` to take a screenshot and save it.

**Comment by toota-toota** [comment]
Should be resolved
